#!/usr/bin/env python3
"""Regenerates Repowire/Design/RelayMarkDots.swift from the relay landing page,
so the app's onboarding mark and the web landing mark are the same dots.
Usage: scripts/mark-dots.py   (run from ios/)
"""
import pathlib
import re

SOURCE = pathlib.Path("../daemon-go/relayserver/assets/landing.html")
TARGET = pathlib.Path("Repowire/Design/RelayMarkDots.swift")

html = SOURCE.read_text()
view_box = re.search(r'class="relay-mark" viewBox="0 0 ([\d.]+) ([\d.]+)"', html)
dots = re.findall(r'<circle cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)"/>', html)
radii = {r for _, _, r in dots}
assert view_box and dots and len(radii) == 1, "landing.html mark changed shape; update this script"
points = ",\n".join(f"        CGPoint(x: {x}, y: {y})" for x, y, _ in dots)
TARGET.write_text(f"""// Generated by scripts/mark-dots.py from daemon-go/relayserver/assets/landing.html.
// Do not edit by hand.
import CoreGraphics

nonisolated enum RelayMarkDots {{
    static let viewBox = CGSize(width: {view_box[1]}, height: {view_box[2]})
    static let radius: CGFloat = {radii.pop()}
    static let points: [CGPoint] = [
{points},
    ]
}}
""")
print(f"{TARGET}: {len(dots)} dots")
